/* Generated by Together */

package com.loyalty.web.vo;

import java.io.Serializable;

import com.loyalty.web.constants.ErrorConstants;

public class TLSErrorVO implements Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 2312399570088104190L;

	private static final String UNIDENTIFIED_ITEM = "Unidentified Item";

	private static final String DEFAULT_USER_FLAG = "T";

	//Error Code to track Error
	private String errorCode = ErrorConstants.UNDEFINED_ERROR;

	//Application creating exception
	private String appCode = UNIDENTIFIED_ITEM;

	//Detailed Message
	private String detailMsgDesc = UNIDENTIFIED_ITEM;

	private String userFlag = DEFAULT_USER_FLAG;

	//Name of object or class where error occurred
	private String errorObjectName = UNIDENTIFIED_ITEM;

	//Name of method where error occurred
	private String errorMethodName = UNIDENTIFIED_ITEM;

	//Determines if error should automatically be written to the log.
	private Boolean logFlag = Boolean.TRUE;

	private String userId = UNIDENTIFIED_ITEM;

	private String userMsgDesc = UNIDENTIFIED_ITEM;

	//Used to hold the "getMessage()" details
	private String msgDesc = UNIDENTIFIED_ITEM;

	/**
	 *  
	 */
	public TLSErrorVO() {
	}

	/**
	 * @param code
	 * @param userFlag
	 * @param message
	 * @param object
	 * 
	 * @deprecated Use another method
	 */
	public TLSErrorVO(String code, String flag, String message, Object object) {
		setErrorCode(code);
		setUserFlag(flag);
		setMsgDesc(message);
		setErrorObjectName(object.toString());
	}

	/**
	 * @param code
	 * @param message
	 * @param object
	 * 
	 * @deprecated Use another method
	 */
	public TLSErrorVO(String code, String message, Object object) {
		setErrorCode(code);
		setMsgDesc(message);
		setErrorObjectName(object.toString());
	}

	/**
	 * @param code
	 * @param message
	 *  
	 */
	public TLSErrorVO(String errorCode, String msgDesc) {
		setErrorCode(errorCode);
		setMsgDesc(msgDesc);
	}

	/**
	 * @return String
	 *  
	 */
	public String getErrorCode() {
		return errorCode;
	}

	/**
	 * @param errorCode
	 *  
	 */
	public void setErrorCode(String errorCode) {
		if (errorCode != null) {
			this.errorCode = errorCode;
		}
	}

	/**
	 * @return String
	 *  
	 */
	public String getUserFlag() {
		return userFlag;
	}

	/**
	 * @param userFlag
	 *  
	 */
	public void setUserFlag(String userFlag) {
		if (userFlag != null) {
			this.userFlag = userFlag;
		}
	}

	/**
	 * @return Returns the appCode.
	 */
	public String getAppCode() {
		return appCode;
	}

	/**
	 * @param appCode
	 *            The appCode to set.
	 */
	public void setAppCode(String appCode) {
		if (appCode != null) {
			this.appCode = appCode;
		}
	}

	/**
	 * @return Returns the detailMsgDesc.
	 */
	public String getDetailMsgDesc() {
		return detailMsgDesc;
	}

	/**
	 * @param detailMsgDesc
	 *            The detailMsgDesc to set.
	 */
	public void setDetailMsgDesc(String detailMsgDesc) {
		if (detailMsgDesc != null) {
			this.detailMsgDesc = detailMsgDesc;
		}
	}

	/**
	 * @return Returns the errorObjectName.
	 */
	public String getErrorObjectName() {
		return errorObjectName;
	}

	/**
	 * @param errorObjectName
	 *            The errorObjectName to set.
	 */
	public void setErrorObjectName(String errorObjectName) {
		if (errorObjectName != null) {
			this.errorObjectName = errorObjectName;
		}
	}

	/**
	 * @return Returns the logFlag.
	 */
	public Boolean getLogFlag() {
		return logFlag;
	}

	/**
	 * @param logFlag
	 *            The logFlag to set.
	 */
	public void setLogFlag(Boolean logFlag) {
		if (logFlag != null) {
			this.logFlag = logFlag;
		}
	}

	/**
	 * @return Returns the msgDesc.
	 */
	public String getMsgDesc() {
		return msgDesc;
	}

	/**
	 * @param msgDesc
	 *            The msgDesc to set.
	 */
	public void setMsgDesc(String msgDesc) {
		if (msgDesc != null) {
			this.msgDesc = msgDesc;
		}
	}

	/**
	 * @return Returns the userId.
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * @param userId
	 *            The userId to set.
	 */
	public void setUserId(String userId) {
		if (userId != null) {
			this.userId = userId;
		}
	}

	/**
	 * @return Returns the userMsgDesc.
	 */
	public String getUserMsgDesc() {
		return userMsgDesc;
	}

	/**
	 * @param userMsgDesc
	 *            The userMsgDesc to set.
	 */
	public void setUserMsgDesc(String userMsgDesc) {
		if (userMsgDesc != null) {
			this.userMsgDesc = userMsgDesc;
		}
	}

	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("    \nTLSException  \n");
		sb.append("          errorCode      : " + errorCode + "\n");
		sb.append("          detailMsgDesc  : " + detailMsgDesc + "\n");
		sb.append("          errorObjectName: " + errorObjectName + "\n");
		sb.append("          errorMethodName: " + errorMethodName + "\n");
		sb.append("          userId         : " + userId + "\n");
		sb.append("          userMsgDesc    : " + userMsgDesc + "\n");
		sb.append("          msgDesc    : " + msgDesc + "\n");
		sb.append("    /TLSException\n");
		return sb.toString();
	}

	/**
	 * @return String
	 * 
	 * @deprecated Use another method
	 */
	public String getCode() {
		return errorCode;
	}

	/**
	 * @param errorCode
	 * 
	 * @deprecated Use another method
	 */
	public void setCode(String errorCode) {
		if (errorCode != null) {
			this.errorCode = errorCode;
		}
	}

	/**
	 * @return String
	 * 
	 * @deprecated Use another method
	 */
	public String getMessage() {
		return msgDesc;
	}

	/**
	 * @param message
	 * 
	 * @deprecated Use another method
	 */
	public void setMessage(String message) {
		if (message != null) {
			this.msgDesc = message;
		}
	}

	/**
	 * @return Object
	 * @deprecated Use another method
	 */
	public Object getObject() {
		try {
			return Class.forName(errorObjectName);
		} catch (Exception onfe) {
			return null;
		}
	}

	/**
	 * @param object
	 * 
	 * @deprecated Use another method
	 */
	public void setObject(String object) {
		if (object != null) {
			this.errorObjectName = object;
		}
	}

	/**
	 * @return Returns the errorMethodName.
	 */
	public String getErrorMethodName() {
		return errorMethodName;
	}

	/**
	 * @param errorMethodName
	 *            The errorMethodName to set.
	 */
	public void setErrorMethodName(String errorMethodName) {
		if (errorMethodName != null) {
			this.errorMethodName = errorMethodName;
		}
	}
}