/* Generated by Together */

package com.loyalty.common.ilclient;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.loyalty.web.constants.Constants;

@Service
public class DataAccessObject {
	
	@Autowired
	DBUtil DBUtil;
	
	public int getProgramID(String webAppName) throws SQLException {
		Statement stmt = null;
		ResultSet rs = null;
		String sql = "";
		long startTime = 0;
		long endTime = 0;
		java.util.Date currentTime = new java.util.Date();
		Connection conn = DBUtil.getConnection(Constants.LOLA_DS);
		Integer programID = null;
		int returnInt = 0;
		String METHOD_NAME = "DataAccessObject: getProgramID() ";
		try {
			// String to call Stored Procedure
			sql = "Select client_program from applications where name = '" + webAppName + "'";
			// prepare stored procedure
			stmt = conn.createStatement();
			rs = stmt.executeQuery(sql);
			while (rs.next()) {
				returnInt = rs.getInt("CLIENT_PROGRAM");
			}
		} finally {
			try {
				if (stmt != null) {
					stmt.close();
				}
				if (rs != null) {
					rs.close();
				}
				if ((conn != null) && (!conn.isClosed())) {
					conn.close();
				}
			} catch (Exception e) {
			}
		}
		return returnInt;
	}
}
