/* Generated by Together */

package com.loyalty.common.ilclient;

public class IntegratedLoginConstants
{
        public static final String INIT_VECTOR_PARAMETER_NAME = "vector";
        public static final String AUTH_URL_PARAMETER_NAME = "authURL";
        public static final String PING_URL_PARAMETER_NAME = "pingURL";
        public static final String LOGOUT_URL_PARAMETER_NAME = "logoutURL";
        public static final String J_SECURITY_CHECK_PARAMETER_NAME = "jSecurityCheckURL";
        public static final String TEMP_J_USERNAME_PARAMETER_NAME = "temp_j_username";
        public static final String J_USERNAME_PARMETER_NAME = "j_username";
        public static final String TEMP_J_PASSWORD_PARAMETER_NAME = "temp_j_password";
        public static final String J_PASSWORD_PARMETER_NAME = "j_password";
        public static final String LOLA_DS = "lolaDS";
        public static final String IL_POINTS_BALANCE="currentPoints";
        public static final String IL_NEXT_YR_PNTS="nextYearsPoints";
        public static final String IL_THIS_YR_PNTS="thisYearsPoints";
        public static final String IL_MEMBER_STATUS="memberStatus";
        public static final String REDIRECT_TO="redirectTo";
        public static final String EMAIL_CAMPAIGN="emailcmp";
        public static final String USE_DISCOVER_SERVICE="useDiscoverService";
}
